name: 🐛 Bug Report
description: Report a bug your facing on the project website
title: "[BUG REPORT]:- (Enter short, one sentence summary of bug here)"
labels: ["bug"]
assignees:
  - KendallDoesCoding
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: no-issues-relating-to-this
    attributes:
      label: Duplicate Issues
      description: Check to make sure there are no existing posts about your problem in the 'issues' section.
      options:
        - label: There are **no existing posts relating to my problem**
          required: true
        - label: There are **existing posts relating to my problem, but the solution given, doesn't work for me.**
          required: false       
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell me, what did you expect to happen?
      placeholder: Tell me what you see!
      value: "Well, I was trying to ... but then ..."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Release version
      description: What version of this program are you using? (If your just running it on the website, don't mention a release version, just say the current version on the website. If your running it locally, and if you downloaded a specific version , please mention)
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: This will allow me to figure out where the issue originates.
      placeholder: Step 1, Step 2, Step 3...
      value: |
             1. 
             2. 
             3. 
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: What platform are you seeing this problem on?
      description: Sometimes, problems can be platform-specific.
      multiple: false
      options:
        - Windows
        - MacOS
        - Linux (can also be ChromeOS)
        - iOS
        - Android
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant console log (if any)
      description: Copy and paste from any relevent console log information about this bug.
      render: shell
