const lyrics = [
  {
    name: "the most wonderful time of the year",
    lyrics: [
      "Its the most wonderful time of the year",
      "With the kids jingle belling and everyone telling youll be of good cheer",
      "Its the most wonderful time of the year",
      "Its the hap- happest season of all",
      "With those holiday greetings",
      "And gay happy meetings when friends come to call",
      "Its the hap- happest season of all",
      "There be parties for hosting",
      "Marshmellows for tosting",
      "And caroling out in the snow",
      "There be scary ghost stories and tales of the glories of Christmases",
      "Long long ago",
      "Its the most wonderful time of the year",
      "There be much misoltoeng",
      "And hearts will be glowing",
      "When loved ones are near",
      "Its the most wonderful time of the year",
      "There be parties for hosting",
      "Marshmellows for tosting",
      "And caroling out in the snow",
      "There be scary ghost stories",
      "And tales of the glories of Christmases long long ago",
      "Its the most wonderful time of the year",
      "There be much misoletong",
      "And hearts will be glowing",
      "When loved ones are near",
      "Its the most wonderful time",
      "Yes the most wonderful time",
      "Its the most wonderful time of he year",
    ],
  },
  {
    name: "little saint nick",
    lyrics: [
      "Ooh",
      "Merry Christmas Saint Nick",
      "Christmas comes this time each year",
      "Ooh, ooh",
      "Well way up North where the air gets cold",
      "There's a tale about Christmas",
      "That you've all been told",
      "And a real famous cat all dressed up in red",
      "And he spends the whole year workin' out on his sled",
      "It's the little Saint Nick (little Saint Nick)",
      "It's the little Saint Nick (little Saint Nick)",
      "Just a little bobsled we call the old Saint Nick",
      "But she'll walk a toboggan with a four speed stick",
      "She's candy apple red with a ski for a wheel",
      "And when Santa hits the gas, man, just watch her peel",
      "It's the little Saint Nick (little Saint Nick)",
      "It's the little Saint Nick (little Saint Nick)",
      "Run run reindeer",
      "Run run reindeer (whoa)",
      "Run run reindeer",
      "Run run reindeer (he don't miss no one)",
      "And haulin' through the snow at a frightening speed",
      "With a half a dozen deer with Rudy to lead",
      "He's got to wear his goggles 'cause the snow really flies",
      "And he's cruisin' every path with a little surprise ",
      "It's the little Saint Nick (little Saint Nick)",
      "It's the little Saint Nick (little Saint Nick)",
      "Ooh",
      "Merry Christmas Saint Nick",
      "(Christmas comes this time each year)",
      "Ooh",
      "Merry Christmas Saint Nick ",
      "(Christmas comes this time each year)",
      "Ooh",
      "Merry Christmas Saint Nick",
      "(Christmas comes this time each year) ",
    ],
  },
  {
    name: "all i want for christmas",
    lyrics: [
      "There is just one thing I need",
      "I don't care about the presents underneath the Christmas tree",
      "I just want you for my own",
      "More than you could ever know ",
      "Make my wish come true",
      "All I want for Christmas is you",
      "Yeah",
      "I don't want a lot for Christmas",
      "There is just one thing I need (and I)",
      "Don't care about the presents underneath the Christmas tree ",
      "I don't need to hang my stocking there upon the fireplace",
      "Santa Claus won't make me happy with a toy on Christmas Day",
      "I just want you for my own",
      "More than you could ever know ",
      "Make my wish come true",
      "All I want for Christmas is you",
      "You, baby",
      "Oh, I won't ask for much this Christmas",
      "I won't even wish for snow (and I)",
      "I'm just gonna keep on waiting underneath the mistletoe",
      "I won't make a list and send it to the North Pole for Saint Nick",
      "I won't even stay awake to hear those magic reindeer click",
      "Cause I just want you here tonight",
      "Holding on to me so tight",
      "What more can I do?",
      "Oh, baby, all I want for Christmas is you",
      "You, baby",
      "Oh-oh, all the lights are shining so brightly everywhere (so brightly, baby)",
      "And the sound of children's laughter fills the air (oh, oh, yeah)",
      "And everyone is singing (oh, yeah)",
      "I hear those sleigh bells ringing",
      "Santa, won't you bring me the one I really need? (Yeah, oh)",
      "Won't you please bring my baby to me?",
      "Oh, I don't want a lot for Christmas",
      "This is all I'm asking for",
      "I just wanna see my baby standing right outside my door",
      "Oh, I just want you for my own",
      "More than you could ever know",
      "Make my wish come true",
      "Oh, baby, all I want for Christmas is you You, baby ",
      "All I want for Christmas is you, baby",
      "All I want for Christmas is you, baby",
      "All I want for Christmas is you, baby",
      " All I want for Christmas (all I really want) is you, baby",
      " All I want (I want) for Christmas (all I really want) is you, baby",
    ],
  },
];
