const lyrics = [
  {
    name: "the most wonderful time of the year",
    lyrics: [
      "Its the most wonderful time of the year",
      "With the kids jingle belling and everyone telling youll be of good cheer",
      "Its the most wonderful time of the year",
      "Its the hap- happest season of all",
      "With those holiday greetings",
      "And gay happy meetings when friends come to call",
      "Its the hap- happest season of all",
      "There be parties for hosting",
      "Marshmellows for tosting",
      "And caroling out in the snow",
      "There be scary ghost stories and tales of the glories of Christmases",
      "Long long ago",
      "Its the most wonderful time of the year",
      "There be much misoltoeng",
      "And hearts will be glowing",
      "When loved ones are near",
      "Its the most wonderful time of the year",
      "There be parties for hosting",
      "Marshmellows for tosting",
      "And caroling out in the snow",
      "There be scary ghost stories",
      "And tales of the glories of Christmases long long ago",
      "Its the most wonderful time of the year",
      "There be much misoletong",
      "And hearts will be glowing",
      "When loved ones are near",
      "Its the most wonderful time",
      "Yes the most wonderful time",
      "Its the most wonderful time of he year",
    ],
  },
];
