// Const the lyrics for all the songs
const lyrics = [{
        name: "the most wonderful time of the year",
        lyrics: [
            "Its the most wonderful time of the year",
            "With the kids jingle belling and everyone telling youll be of good cheer",
            "Its the most wonderful time of the year",
            "Its the hap- happest season of all",
            "With those holiday greetings",
            "And gay happy meetings when friends come to call",
            "Its the hap- happest season of all",
            "There be parties for hosting",
            "Marshmellows for tosting",
            "And caroling out in the snow",
            "There be scary ghost stories and tales of the glories of Christmases",
            "Long long ago",
            "Its the most wonderful time of the year",
            "There be much misoltoeng",
            "And hearts will be glowing",
            "When loved ones are near",
            "Its the most wonderful time of the year",
            "There be parties for hosting",
            "Marshmellows for tosting",
            "And caroling out in the snow",
            "There be scary ghost stories",
            "And tales of the glories of Christmases long long ago",
            "Its the most wonderful time of the year",
            "There be much misoletong",
            "And hearts will be glowing",
            "When loved ones are near",
            "Its the most wonderful time",
            "Yes the most wonderful time",
            "Its the most wonderful time of he year",
        ],
    },
    {
        name: "little saint nick",
        lyrics: [
            "Ooh",
            "Merry Christmas Saint Nick",
            "Christmas comes this time each year",
            "Ooh, ooh",
            "Well way up North where the air gets cold",
            "There's a tale about Christmas",
            "That you've all been told",
            "And a real famous cat all dressed up in red",
            "And he spends the whole year workin' out on his sled",
            "It's the little Saint Nick (little Saint Nick)",
            "It's the little Saint Nick (little Saint Nick)",
            "Just a little bobsled we call the old Saint Nick",
            "But she'll walk a toboggan with a four speed stick",
            "She's candy apple red with a ski for a wheel",
            "And when Santa hits the gas, man, just watch her peel",
            "It's the little Saint Nick (little Saint Nick)",
            "It's the little Saint Nick (little Saint Nick)",
            "Run run reindeer",
            "Run run reindeer (whoa)",
            "Run run reindeer",
            "Run run reindeer (he don't miss no one)",
            "And haulin' through the snow at a frightening speed",
            "With a half a dozen deer with Rudy to lead",
            "He's got to wear his goggles 'cause the snow really flies",
            "And he's cruisin' every path with a little surprise ",
            "It's the little Saint Nick (little Saint Nick)",
            "It's the little Saint Nick (little Saint Nick)",
            "Ooh",
            "Merry Christmas Saint Nick",
            "(Christmas comes this time each year)",
            "Ooh",
            "Merry Christmas Saint Nick ",
            "(Christmas comes this time each year)",
            "Ooh",
            "Merry Christmas Saint Nick",
            "(Christmas comes this time each year) ",
        ],
    },
    {
        name: "all i want for christmas",
        lyrics: [
            "I don't want a lot for Christmas",
            "There is just one thing I need",
            "I don't care about the presents underneath the Christmas tree",
            "I just want you for my own",
            "More than you could ever know ",
            "Make my wish come true",
            "All I want for Christmas is you",
            "Yeah",
            "I don't want a lot for Christmas",
            "There is just one thing I need (and I)",
            "Don't care about the presents underneath the Christmas tree ",
            "I don't need to hang my stocking there upon the fireplace",
            "Santa Claus won't make me happy with a toy on Christmas Day",
            "I just want you for my own",
            "More than you could ever know ",
            "Make my wish come true",
            "All I want for Christmas is you",
            "You, baby",
            "Oh, I won't ask for much this Christmas",
            "I won't even wish for snow (and I)",
            "I'm just gonna keep on waiting underneath the mistletoe",
            "I won't make a list and send it to the North Pole for Saint Nick",
            "I won't even stay awake to hear those magic reindeer click",
            "Cause I just want you here tonight",
            "Holding on to me so tight",
            "What more can I do?",
            "Oh, baby, all I want for Christmas is you",
            "You, baby",
            "Oh-oh, all the lights are shining so brightly everywhere (so brightly, baby)",
            "And the sound of children's laughter fills the air (oh, oh, yeah)",
            "And everyone is singing (oh, yeah)",
            "I hear those sleigh bells ringing",
            "Santa, won't you bring me the one I really need? (Yeah, oh)",
            "Won't you please bring my baby to me?",
            "Oh, I don't want a lot for Christmas",
            "This is all I'm asking for",
            "I just wanna see my baby standing right outside my door",
            "Oh, I just want you for my own",
            "More than you could ever know",
            "Make my wish come true",
            "Oh, baby, all I want for Christmas is you You, baby ",
            "All I want for Christmas is you, baby",
            "All I want for Christmas is you, baby",
            "All I want for Christmas is you, baby",
            " All I want for Christmas (all I really want) is you, baby",
            " All I want (I want) for Christmas (all I really want) is you, baby",
        ],
    },
    {
        name: "baby its cold outside",
        lyrics: [
            "I really can't stay",
            "Baby it's cold outside",
            "I gotta go away",
            "Baby it's cold outside",
            "This evening has been",
            "Been hoping that you'd dropped in",
            "So very nice",
            "I'll hold your hands they're just like ice",
            "My mother will start to worry",
            "Beautiful what's your hurry?",
            "My father will be pacing the floor",
            " Listen to the fireplace roar",
            "So really I'd better scurry ",
            "Beautiful please don't hurry",
            "Well maybe just a half a drink more",
            "I'll put some records on while I pour",
            "The neighbors might think",
            "Baby it's bad out there",
            "Say what's in this drink?",
            "No cabs to be had out there",
            "I wish I knew how",
            "Your eyes are like starlight now",
            "To break this spell",
            "I'll take your hat, your hair looks swell",
            "Why thank you",
            "I ought to say no, no, no sir",
            "Mind if move in closer?",
            "At least I'm gonna say that I tried",
            "What's the sense of hurting my pride?",
            "I really can't stay",
            "Baby don't hold out",
            "Baby it's cold outside",
            "Ah, you're very pushy you know?",
            "I like to think of it as opportunistic",
            "I simply must go",
            "Baby it's cold outside",
            "The answer is no",
            "But baby it's cold outside",
            "The welcome has been",
            "How lucky that you dropped in",
            "So nice and warm",
            "Look out the window at that storm",
            "My sister will be suspicious",
            "Gosh your lips look delicious!",
            "My brother will be there at the door",
            "Waves upon a tropical shore",
            "My maiden aunt's mind is vicious",
            "Gosh your lips are delicious!",
            "Well maybe just a cigarette more",
            "Never such a blizzard before",
            "And I don't even smoke",
            "I've got to get home",
            "Baby you'll freeze out there",
            " Say lend me your comb",
            "It's up to your knees out there!",
            "You've really been grand,",
            "I feel when I touch your hand",
            "But don't you see? ",
            "How can you do this thing to me?",
            "There's bound to be talk tomorrow",
            "Think of my life long sorrow!",
            "At least there will be plenty implied",
            "If you caught pneumonia and died!",
            "I really can't stay",
            "Get over that old out",
            "Baby it's cold",
            "Baby it's cold outside",
            "Okay fine, just another drink then",
            "That took a lot of convincing!",
        ],
    },
    {
        name: "christmas song",
        lyrics: [
            "Chestnuts roasting on an open fire",
            "Jack Frost nipping at your nose",
            "Yuletide carols being sung by a choir",
            "And folks dressed up like Eskimos",
            "Everybody knows a turkey and some mistletoe",
            "Help to make the season bright",
            "Tiny tots with their eyes all aglow",
            "Will find it hard to sleep tonight",
            "They know that Santa's on his way",
            "He's loaded lots of toys and goodies on his sleigh",
            "And every mother's child is gonna spy",
            "To see if reindeers really know how to fly",
            "And so I'm offering this simple phrase",
            "To kids from one to ninety-two",
            "Although it's been said many times, many ways",
            "Merry Christmas to you",
            "And so I'm offering this simple phrase",
            "To kids from one to ninety-two",
            "Although it's been said many times, many ways",
            "Merry Christmas to you",
        ],
    },
    {
        name: "last christmas",
        lyrics: [
            "Oh, oh-oh, ooh-oh-oh-oh",
            "Ah-ah",
            "Last Christmas, I gave you my heart",
            "But the very next day, you gave it away",
            "This year, to save me from tears",
            "I'll give it to someone special",
            "Last Christmas, I gave you my heart",
            "But the very next day, you gave it away (you gave it away)",
            "This year, to save me from tears",
            "I'll give it to someone special (special)",
            "Once bitten and twice shy",
            "I keep my distance, but you still catch my eye",
            "Tell me, baby, do you recognize me?",
            "Well, it's been a year, it doesn't surprise me",
            "'Merry Christmas, ' I wrapped it up and sent it",
            "With a note saying 'I love you, ' I meant it",
            "Now I know what a fool I've been",
            "But if you kissed me now, I know you'd fool me again",
            "Last Christmas, I gave you my heart",
            "But the very next day, you gave it away (you gave it away)",
            "This year, to save me from tears",
            "I'll give it to someone special (special)",
            "Last Christmas, I gave you my heart",
            "But the very next day, you gave it away",
            "This year, to save me from tears",
            "I'll give it to someone special (special)",
            "Oh",
            "Oh, oh, baby",
            "A crowded room, friends with tired eyes",
            "I'm hiding from you and your soul of ice",
            "My God, I thought you were someone to rely on",
            "Me? I guess I was a shoulder to cry on",
            "A face on a lover with a fire in his heart",
            "A man under cover but you tore me apart",
            "Ooh, ooh, now I've found a real love",
            "You'll never fool me again",
            "Last Christmas, I gave you my heart",
            "But the very next day, you gave it away (you gave it away)",
            "This year, to save me from tears",
            "I'll give it to someone special (special)",
            "Last Christmas, I gave you my heart",
            "But the very next day, you gave it away",
            "This year, to save me from tears ",
            "I'll give it to someone special (special!)",
            "A face on a lover with a fire in his heart (I gave you mine)",
            " A man under cover, but you tore him apart",
            "Maybe next year, we'll give it to someone",
            "I'll give it to someone special (special!)",
            "So long!",
        ],
    },
];
