name: png to jpg
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jruipinto/ImageMagick-action@v1
        with:
          command: mogrify -format jpg images/*.png
      - uses: cmgriffing/scully-gh-pages-action@v9
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-branch: master
          build-args: --base-href
